name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Instala dependências
        run: npm install  # Se for um projeto Node.js. Remova se não precisar.

      - name: Cria os arquivos para Deploy
        run: |
          mkdir -p output
          rsync -av --progress ./ output --exclude output

      - name: Faz upload dos arquivos para deploy
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output

      - name: Faz deploy no branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
