name: Deploy para paginas do GitHub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositorio
        uses: actions/checkout@v3

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Cria os arquivos para Deploy
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

      - name: Publica no GitPages
        uses: actions/deploy-pages@v1
