name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Cria os arquivos para Deploy
        run: |
          mkdir -p output
          rsync -av --progress ./ output --exclude output

      - name: Upload dos arquivos para deploy
        uses: actions/upload-pages-artifact@v1
        with:
          path: output

      - name: Publica no GitHub Pages
        uses: actions/deploy-pages@v2
