name: Deploy para paginas do GitHub

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checa o repositorio
        uses: actions/checkout@v3

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Cria os arquivos para Deploy
        run: |
          mkdir output
          # Copia os arquivos e pastas, mas ignora a pasta 'output'
          shopt -s extglob
          cp -r !(output) output/

      - name: Publica no GitHub Pages
        uses: actions/deploy-pages@v1
