name: Teste Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checa o repositório
        uses: actions/checkout@v3

      - name: Configura GitHub Pages
        uses: actions/configure-pages@v3

      - name: Publica no GitHub Pages
        uses: actions/deploy-pages@v2
