name: Deploy Jekyll para GitHub Pages

on:
  push:
    branches: 
      - main   # Aciona apenas para o branch main
    paths-ignore:
      - 'gh-pages/**/*'  # Ignora qualquer alteração na branch gh-pages
  pull_request:
    branches:
      - main   # Aciona pull requests para o branch main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Build do site no container Jekyll
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Faz deploy para o branch gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        # Certifique-se de que você está publicando para o caminho correto
        branch: gh-pages  # Confirma que o deploy está sendo feito na branch gh-pages
