name: Deploy Jekyll para GitHub Pages

on:
  push:
    branches:
      - main  # Aciona o deploy apenas quando há push para o branch main
    paths-ignore:
      - 'gh-pages/**/*'  # Ignora qualquer alteração na branch gh-pages
  pull_request:
    branches:
      - main  # Aciona o deploy para PRs no branch main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v4

    - name: Limpar artefatos antigos (se houver)
      run: |
        rm -rf _site/*  # Limpa qualquer conteúdo antigo antes de construir

    - name: Build do site no container Jekyll
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    - name: Verificar se houve alterações no conteúdo gerado
      run: |
        git diff --exit-code || echo "Alterações detectadas, prosseguindo com deploy."
      
    - name: Faz deploy para o branch gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site  # A pasta de publicação
        branch: gh-pages  # A branch onde o conteúdo será publicado
        no_ci: true  # Impede que o commit de deploy dispare outro workflow
